MODEL:
  TYPE: SPECTRAL_FORMER
  NAME: spectral_former_ViT
  DROP_PATH_RATE: 0.2
  SPECTRAL_FORMER:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 6
    DEPTH: 12
    MODE: 'ViT'
  LABEL_SMOOTHING: 0.0
  LEARNING_RATE: 2.5e-5
DATA:
  IMG_SIZE: 224
  PATCH_SIZE: 5
  MASK_PATCH_SIZE: 4
  MASK_RATIO: 0.6
  DATASET: huston13-18
  LEARNING_RATE: 2.5e-5
  SAMPLE_NUM: 180
  PATCH_DIM: 512
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 10
  BASE_LR: 8e-4
  WARMUP_LR: 2.5e-7
  MIN_LR: 2.5e-7
  WEIGHT_DECAY: 0.05
  LAYER_DECAY: 0.7
  FINETUNE:
    BASE_LR: 8e-4
    WARMUP_LR: 2.5e-7
    MIN_LR: 2.5e-7
PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: spectral_former
IS_HSI: TRUE
IS_DIST: False
AUG:
  MIXUP: 0.0