MODEL:
  TYPE: vit
  NAME: demo
  DROP_PATH_RATE: 0.2
  VIT:
    EMBED_DIM: 512
    IN_CHANS: 48
    DEPTH: 6
    NUM_HEADS: 12
    USE_APE: True
    USE_RPB: False
    USE_SHARED_RPB: False
    USE_MEAN_POOLING: False
  DROP_RATE: 0.
DATA:
  IMG_SIZE: 5
  MASK_PATCH_SIZE: 4
  MASK_RATIO: 0.6
  DATASET: huston13-18
  LEARNING_RATE: 2.5e-5
  SAMPLE_NUM: 180
  PATCH_DIM: 512
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 10
  BASE_LR: 1.25e-3
  WARMUP_LR: 2.5e-7
  MIN_LR: 2.5e-7
  WEIGHT_DECAY: 0.05
  LAYER_DECAY: 0.7
  FINETUNE:
    BASE_LR: 1.25e-3
    WARMUP_LR: 2.5e-7
    MIN_LR: 2.5e-7
PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: simmim_finetune__Dtransformer_finetune
IS_HSI: TRUE
IS_DIST: False
AUG:
  MIXUP: 0.0