MODEL:
  TYPE: swin
  NAME: swin_spatial_houston
  DROP_PATH_RATE: 0.2
  SPATIAL_PATCH_DIM: 512
  SPECTRAL_PATCH_DIM: 512
  CLASSIFIER_IN_DIM: 1024
  LABEL_SMOOTHING: 0.0
  LEARNING_RATE: 2.5e-5
CLASSIFIER:
  MODE: spatial
  ATTENTION:
    DIM: 512
    DEPTH: 2
DATA:
  DIM: 48
  MODE: spatial
  IMG_SIZE: 224
  MASK_PATCH_SIZE: 6
  MASK_RATIO: 0.3
  DATASET: houston
  LEARNING_RATE: 2.5e-5
  SAMPLE_NUM: 180
  PATCH_DIM: 512
  SPECTRAL:
    CHANNEL_DIM: 48
  SPATIAL:
    PCA: False
    COMPONENT_NUM: 3
  SPATIAL_ORIGIN: True
  IS_MASK: False
TRAIN:
  EPOCHS: 100
  RF_ETA: 80
  WARMUP_EPOCHS: 10
  BASE_LR: 8e-4
  WARMUP_LR: 2.5e-7
  MIN_LR: 2.5e-7
  WEIGHT_DECAY: 0.05
  LAYER_DECAY: 0.7
  FINETUNE:
    BASE_LR: 8e-4
    WARMUP_LR: 2.5e-7
    MIN_LR: 2.5e-7
PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: simmim_finetune__Dtransformer_finetune
IS_HSI: TRUE
IS_DIST: False
AUG:
  MIXUP: 0.0